use_frameworks!

platform :ios, '9.0'

target 'SMSkinMagnifierSDK_Example' do
  pod 'SMSkinMagnifierSDK', :path => '../'
#
#  target 'SMSkinMagnifierSDK_Tests' do
#    inherit! :search_paths
#
#    
#  end
end
